### ISSUE TITLE
TypeScript instructions don't seem to cover all props

### ISSUE THREAD

**Issue by kaiyoma** [Authress-Engineering/openapi-explorer#162]
I followed the TypeScript instructions (https://github.com/Rhosys/openapi-explorer/blob/f054e5fafe48563913419633af46f8edbe92d5ba/docs/troubleshooting.md#typescript) and it mostly works, but `collapse` is still being reported as an error:

![image](https://github.com/Rhosys/openapi-explorer/assets/10719780/9d6c77a8-4a01-40bf-8d23-d0a2c6c4b2f4)

**Comment by wparad** [comment]
Can you share a minimal reproduction of this problem so we can investigate?

**Comment by kaiyoma** [comment]
```
import 'openapi-explorer';
import type { FunctionComponent } from 'react';
import React from 'react';

declare global {
  namespace JSX {
    interface IntrinsicElements {
      'openapi-explorer': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement>;
    }
  }
}

const ApiExplorer: FunctionComponent = () => {
  return (
    <openapi-explorer
      collapse={true}
      enable-console={false}
      show-authentication={false}
      show-server-selection={false}
      spec-url='/web/api/api_json/api-docs.json'
      use-path-in-nav-bar={true}
    />
  );
};

export default ApiExplorer;
```

**Comment by kaiyoma** [comment]
To be clear, the component is working. It's just that the type checker is throwing an error. I think the real solution here is that either this tag needs proper types defined, or needs to be implemented as a proper React component.

**Comment by wparad** [comment]
Web components are a global standard that everything supports, so technically it is already a proper react component. Actually the issue here as you pointed out is your type checker. So the example code you provided actually works for me. 

The problem isn't the component code it's the type checking system. So can you share the minimal repro which includes the tsconfig, webpack.config, babel, pwc, vite config, etc.. including all the relevant technologies here, because the problem is going to almost certainly be with one of them.

I'm trying out some options and I'm wondering what happens if we just specify the properties of the OpenAPI Explorer:

```tsx
interface OpenApiExplorerProps {
  collapse?: boolean
}

declare global {
  namespace JSX {
    interface IntrinsicElements {
      'openapi-explorer': OpenApiExplorerProps & React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement>;
    }
  }
}
```

Does that work?
