### ISSUE TITLE
Unable to display the downloaded images as a response

### ISSUE THREAD

**Issue by jShiwaniGupta** [Authress-Engineering/openapi-explorer#206]
As a response we are expecting an png/pdf image but the explorer is unable to display the downloaded content(pdf/png/jpeg etc)

**Comment by wparad** [comment]
Would you kindly be able to share a minimal reproduction of the problem so that we can validate the issue and fix it?

**Comment by jShiwaniGupta** [comment]
an endpoint which suppose to download a png file 
mediaType = MediaType.application/octet-stream

But instead on UI swagger page we are getting response 
Response Status: sr.extension is not a function (Check the browser network tab for more information.)
Execution Time: 1637ms

while in Network tab if we check we are getting 200 success response code and response image also.

**Comment by wparad** [comment]
@jShiwaniGupta, your media type must be set to the valid `png` media type which in this case would be `image/png`. then it will be displayed correctly.

If you still are not able to validate this, please include a fully working openapi specification that can be tested.

As you can imagine support issues with the open api specification 3.0, is a full time job, given the number of users that we have. Attempting to identify and validate the problem is nearly impossible without a working demo. In general we recommend creating a fully working reproduction by providing a minimal working spec, or a github repository that contains the working example. Right now, as we don't have your spec we are unable to provide further assistance until that time.

Thanks,
Warren
