### ISSUE TITLE
Changing the accept header to execute is not UX friendly

### ISSUE THREAD

**Issue by gdec31** [Authress-Engineering/openapi-explorer#232]
Changing the accept header works well. But is not really user friendly.
Several of my users don't really understand how to change the format type of the endpoint.

**Actual behavior:**
![image](https://github.com/Authress-Engineering/openapi-explorer/assets/26168420/d4e8ca5a-67af-4821-b38d-1f369e3d0d04)

**Expected behavior:**

We could have something like this : 
![image](https://github.com/Authress-Engineering/openapi-explorer/assets/26168420/9125fc01-6395-4484-9505-1752411e6788)

**Comment by wparad** [comment]
This is actually configurable by the Accept header, but it isn't obvious because of how it is. Now the accept header will automatically added into the request section to actually support this in a UX friendly way:

![image](https://github.com/Authress-Engineering/openapi-explorer/assets/5056218/4c665de4-6bd5-4fa1-b420-046ac01050b9)

This is of course customizeable by overwriting the Accept header configuration with your own.
