### ISSUE TITLE
Array schema name on the model

### ISSUE THREAD

**Issue by gdec31** [Authress-Engineering/openapi-explorer#235]
Hi,

Sorry I should see that yesterday when I write the #231.

The sub arrays name in the schema are not set too.

```javascript
..
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "categories": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/DtoCategory"
            }
          }, ..
``` 
Actual behavior: 
![image](https://github.com/Authress-Engineering/openapi-explorer/assets/26168420/7aa7107a-cd3e-48f5-a0c0-4ed1887e24ba)

Expected behavior:
![image](https://github.com/Authress-Engineering/openapi-explorer/assets/26168420/128db94d-d635-4a93-84b0-527784c6e34a)

**Comment by wparad** [comment]
Unfortunately there is no room to display in a pleasing way an additional property here. We could display that name when the object is collapsed, instead of showing `[{...}]` it should show `[{ DtoCategory }]` instead.

I'm not sure there is really an alternative here as a floating type isn't going to cut it here. I can recommend two better choices though:
1. Define the `title` attribute of your `categories` property, and it will be shown on the right hand side:
![image](https://github.com/Authress-Engineering/openapi-explorer/assets/5056218/75c9d52f-f81b-40b5-99d3-e9c19b4a94c2)

like this:
```json
"error": {
    "type": "array",
    "title": "DtoResponse",
    "items": {
        "$ref": "#/components/schemas/DtoResponse"
    }
},
```

2. [Preferred] Switch to the advanced `Table` view of the spec, which includes these by default:
 
![image](https://github.com/Authress-Engineering/openapi-explorer/assets/5056218/a30a406a-b40e-43ae-9eb0-5850378f4029)

Fwiw, we could support a potentially 3rd option as well:
3. high fidelity alternatives to improve this view that correctly handle all the edge cases.

I don't think that's really an option I want to push on people, but if a design comes up that our team likes, I'm sure we wouldn't hesitate to throw it together.

Given those, I don't think there is anything concrete that we could do here, so I plan to close this issue. If for some reason the `table` view has any issues, we would be more than happy to add any and all improvements to it.

**Comment by gdec31** [comment]
It's ok to use table.
Thank you
