### ISSUE TITLE
Missing description for tag

### ISSUE THREAD

**Issue by majoshi1** [Authress-Engineering/openapi-explorer#255]
I tried [this](https://rapidocweb.com/specs/petstore_extended.yaml) sample pet store yaml in [demo](https://authress-engineering.github.io/openapi-explorer/). It can expand/collapse by default. But it does not show tag description. I checked [docs](https://github.com/Authress-Engineering/openapi-explorer/blob/release/2.2/docs/documentation.md) for any custom configuration. But I only see `use-path-in-nav-bar`. Any idea?

[Here](https://majoshi1.github.io/rapidocweb/examples/focused-mode.html#tag--pet) a working sample with expected behavior using [forked](https://www.npmjs.com/package/@majoshi1/rapidoc) rapidoc component.

**Comment by wparad** [comment]
I was just playing around with this, and it seems that the description is what ends up on the dedicated `Tag` page. I believe that's because the tag description supports markdown and can be very long.

I haven't looked at this, but I believe there is a link to the `tag` page which includes all that data and some additional `<slot>` which might be what you are looking for. I can imagine that rendering the description inline usually isn't the best solution. 

There's something I don't like there, so I'm actually going to put a PR to fix that.

![Peek 2024-06-09 10-32](https://github.com/Authress-Engineering/openapi-explorer/assets/5056218/0ccc404a-0eb4-4ae5-a57d-d4edb9ada19a)

**Comment by majoshi1** [comment]
Here are some more details for reference. [Here](https://majoshi1.github.io/rapidocweb/examples/focused-mode.html#tag--pet) is a working sample with expected behavior using [forked](https://www.npmjs.com/package/@majoshi1/rapidoc) rapidoc component. It uses [this](https://majoshi1.github.io/rapidocweb/specs/petstore_extended.yaml) sample pet store API specs.

A few things happen when user clicks on a tag on the left panel.
-Tag expands and shows all available actions on left panel.
-Tag description is shown on right panel.
-Any other open tag is collapsed.

Below are the screenshots for reference, from the working example [here](https://majoshi1.github.io/rapidocweb/examples/focused-mode.html#tag--pet).


- Screenshot 1
Action: I clicked on 'Store' tag in left panel. 
Result: That tag is expanded in the left panel. The description is shown on the right panel.

![image](https://github.com/Authress-Engineering/openapi-explorer/assets/292394/1a8005d1-ec29-4210-95b6-6b509a59d945)


- Screenshot 2
Action: Then, I clicked on 'User' tag. 
Result: The 'User' tag is expanded in left panel. The description is shown on right panel. Also, the 'Store' tag is collapsed. 

![image](https://github.com/Authress-Engineering/openapi-explorer/assets/292394/218fe267-8dfa-4500-8f4f-90a3fe9015aa)

I hope this helps.

**Comment by Xarno** [comment]
Thanks :) was just about to report exactly this too.

**Comment by wparad** [comment]
Hello @Xarno, the description triggers a full page dedicated to the `tag` in question as well as some additional slots if necessary. Further there is also a new slot available in each of the operations body's under the `Tag` for a shorter summary of the description if desired.
