### ISSUE TITLE
Execute request removes path prefix before execution

### ISSUE THREAD

**Issue by Kharonus** [Authress-Engineering/openapi-explorer#260]
Ahoi,

I have an issue with the inbuilt request execution on my application with the embedded openapi-explorer.

#### Issue

- My app runs under a path prefix: `http://localhost/subfolder`
- The openapi-explorer is embedded under the route `/api/docs` resulting in the full URL `http://localhost/subfolder/api/docs`
- If I execute any request from any specification, the resulting request URL is: `http://localhost/api/v3/projects`
  - the specification contains the path objects to be exactly those: `/api/v3/...`
- application path prefix is not honored, when constructing request URLs

The base of my issue is a bit vague. Is this the expected behaviour? Is there an option to set a static path prefix for the OpenAPI paths? Where in the openapi-explorer code are those request URLs constructed?

#### Hint

I'm pretty sure, it is not connected, but October last year I had another issue related to URLs: https://github.com/Authress-Engineering/openapi-explorer/issues/202 . This one was fully clarified and explained, and I hope, I can achieve something similar with the current issue.

Many thanks and best regards,
kharonus

**Comment by wparad** [comment]
It's important to remember, where the docs are being hosted `/subfolder/api/docs` has nothing to do with the api server targets defined in your spec.

Assuming `subfolder` is the prefix you want to prefix all the paths, then make sure to set the `servers` array in the openapi specification to include that part:

```json
"servers": [{
  "url": "http://localhost/subfolder"
}]
```

The full api path is constructed by the "Selected Server URL" and the defined Path. The Server URL list is pulled almost directly from the OpenAPI Spec `servers` property, but there are some fallback options available in the `spec-parser.js`, if you are curious how that works.

As this is the expected behavior, I'm going to close this issue, but if you are still seeing unexpected behavior/difficult to rectify/implement behavior, please feel free to continue to comment in here (and we can reopen if necessary)

**Comment by Kharonus** [comment]
All fine, you are right. Also makes a lot of sense, just sometimes one is misled by some other assumptions. ^^ thanks for taking the time to clarify this.

**Comment by wparad** [comment]
no problem. Glad it all makes sense.
